.\build\ArcTest > TestResults\ArcTest.txt
.\build\CircleTest > TestResults\CircleTest.txt
.\build\EllipseTest > TestResults\EllipseTest.txt
.\build\FillEllipseTest > TestResults\FillEllipseTest.txt
.\build\FillPieTest > TestResults\FillPieTest.txt
.\build\FillRoundRectTest > TestResults\FillRoundRectTest.txt
.\build\FloodFillTest > TestResults\FloodFillTest.txt
.\build\LineTest > TestResults\LineTest.txt
.\build\NormalizeRadianTest > TestResults\NormalizeRadianTest.txt
.\build\PieTest > TestResults\PieTest.txt
.\build\PolygonTest > TestResults\PolygonTest.txt
.\build\RoundRectTest > TestResults\RoundRectTest.txt
.\build\SubImageTest > TestResults\SubImage.txt
